---
title: Global Sequence Alignment
author: 'Desiree '
date: '2019-12-09'
slug: global-sequence-alignment
categories: []
tags: []
description: ''
---

## Sequence Aligning 

Global sequence alignment was one of the last concepts that we covered in Python and it was one of my favorite. The significance of global sequence alignment is that it is mainly used to demonstrate the highly conserved regions of protein alignment. It is known that when a sequence is highly conserved then it has important evolutionary properties for the survival of said organism. 

## The NeedleMan-Wusch Algorithm 
This is the algorithm used in bioinformatics in order to align proteins and give a proper scoring system. A matrix must first be created with one sequence along the horizontal and another along the vertical with a gap to start. To fill the cells, there can be a gap, a mismatch or a match. A match results when you have two amino acids that align. When you go diagonally, there can be a match or mismatch but it is important to choose the one that gives you the highest score. Going vertically or horizontally will result in a gap which decreases your score depending on the scoring system.


